### ISSUE TITLE
Name conflict (HMM vs. HiddenMarkovModel)

### ISSUE THREAD

**Issue by baggepinnen** [ahwillia/HiddenMarkovModel.jl#1]
One must change the name of the folder containing the package from HMM to HiddenMarkovModel for julia to find the module named HiddenMarkovModel if one downloads the package using Pkg.clone()

**Comment by ahwillia** [comment]
Done. There was another "HiddenMarkovModel" on github, but it doesn't seem to be under development, so I'm not too worried about the conflict.
