### ISSUE TITLE
calc_stats not exported

### ISSUE THREAD

**Issue by baggepinnen** [ahwillia/HiddenMarkovModel.jl#2]
If one is interested in the state sequence, the function calc_stats is of interest since it does the necessary forward and backward passes and calculates the smoothed state sequence `g`. This function is however not exported.

**Comment by ahwillia** [comment]
Nice idea. I made a new function `smoothed_forward_backward` that does this calculation and just returns `g`, rather than the other garbage that is calculated.

See: https://github.com/ahwillia/HiddenMarkovModel.jl/commit/314c09052ca990c167035fcbfdc476156845b7f7

**Comment by ahwillia** [comment]
Thanks for the feedback on this -- let me know if you have any other thoughts. Pull requests also welcome :)
