### ISSUE TITLE
function re_estimate! assumes all distributions are of same type as first distribution

### ISSUE THREAD

**Issue by baggepinnen** [ahwillia/HiddenMarkovModel.jl#3]
dist_type = typeof(hmm.B[1]) is put outside the for-loop. If moved inside, different distributions could be supported.

**Comment by ahwillia** [comment]
Closed by: https://github.com/ahwillia/HiddenMarkovModel.jl/commit/39243b4c34a802b4eecf2b9d65f7003ef4b08856
